pdb:
  create: true
  minAvailable: 1
  maxUnavailable: ""
  # This is a beta feature, so it's not enabled by default.
  unhealthyPodEvictionPolicy: 

serviceAccount:
  create: true

autoscaling:
  enabled: true

ingress:
  enabled: true
  hosts:
    - host: test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
