pdb:
  create: true
  minAvailable: 1
  maxUnavailable: ""
  unhealthyPodEvictionPolicy: AlwaysAllow

serviceAccount:
  create: true

autoscaling:
  enabled: true

ingress:
  enabled: true
  hosts:
    - host: test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
