{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "varnish-cache.fullname" . }}
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gotenberg.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{- if .Values.networkPolicy.allowIngress }}
  - {}
{{- else }}
  {{- toYaml .Values.networkPolicy.extraIngress | nindent 2 }}
{{- end }}
  egress:
{{- if .Values.networkPolicy.allowEgress }}
  - {}
{{- else }}
  {{- toYaml .Values.networkPolicy.extraEgress | nindent 2 }}
{{- end }}
{{- end }}
